### ISSUE TITLE
OMK created OSM files with tags of null values

### ISSUE THREAD

**Issue by skorasaurus** [AmericanRedCross/openmapkit#10]
Hi, 

Awesome work! 

I noticed in one of the pictures in Dale's presentation this morning was an OSM file in JOSM. 
In the picture that was created in OMK and opened in josm, contained buildings had several tags which had an empty or null value in them.  

Here was an example of what I'm trying to explain except there would be nothing there where the 0's are. 
(you can't manually add a tag with a null value in JOSM). 
![selection_039](https://cloud.githubusercontent.com/assets/955351/6606099/5cc3f418-c7f2-11e4-83b3-6821eaaab80b.png)

cc @dalekunce

**Comment by dalekunce** [comment]
@skorasaurus thanks for pointing this out. One of our next sprints is going to be on constraints. We will be driving to have OMK use a lot of the same constraint logic as ODK with a slight OSM bent. Check back in a few weeks.

**Comment by hallahan** [comment]
Good catch, this is an easy fix.

We need to check to see if a value is null in the XML Writer here:

https://github.com/AmericanRedCross/openmapkit/blob/master/MapboxAndroidSDK/src/main/java/com/spatialdev/osm/model/OSMElement.java#L152
