### ISSUE TITLE
Ona API: Form OSM edit set should show latest osm element only

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKit#2]
We can't delete the old OSM XML, because that would corrupt the workflow of form submission. If I were to reselect a previously edited OSM element in a new form instance and deleted the old one, there would be an error on the submission to Ona.

Instead, we need to add logic to Ona's API so that when we get the set of OSM edits for a given form, the latest edit for a given feature should be included, and the older ones should not.

**Comment by hallahan** [comment]
@mberg @ukanga - make sense?

**Comment by hallahan** [comment]
@mberg @ukanga - I'm thinking I might extend this logic in the app itself. Show only the latest edit of there are multiple edits for the same feature.

**Comment by ukanga** [comment]
It makes sense, and you are right we will need to introduce this to OSM api endpoint.

**Comment by dalekunce** [comment]
@hallahan can I close this issue.

**Comment by hallahan** [comment]
I do not think this issue is completed, but it should be in the onadata repo if we want to acknowledge this.
