### ISSUE TITLE
Ability to select or restrict OSM file used

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/openmapkit#27]
Sometimes user should only have the option to edit roads or buildings. Need to be able to hide other OSM files from the survey and user.

**Comment by hallahan** [comment]
Do we want to restrict based off of tags or what OSM XML file we are using or both?

**Comment by hallahan** [comment]
It would be good to have a button in the UI to zoom to the extent of a given OSM file so we know where it is.

**Comment by hallahan** [comment]
When unchecking a given data set (OSM File), we need to take that data out of the model. I am evaluating the pros and cons of either
    a) iterating through what is in the spatial index and removing elements
    b) rebuilding the spatial index

**Comment by hallahan** [comment]
Note, this does not include the new "Control Panel" UI I was brainstorming. This adds another button on the top of the app. Consider this temporary.
