### ISSUE TITLE
Android based way to fetch OSM XML from Overpass

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKit#28]
We should have UI on the android phone to download OSM XML dynamically from the Overpass API:

This can be used instead of doing this:

https://github.com/AmericanRedCross/openmapkit/wiki/OSM-Data-from-the-Overpass-API

**Comment by hallahan** [comment]
For future reference, here's how we can resume downloads that have been stopped:

http://stackoverflow.com/questions/6237079/resume-http-file-download-in-java

Initial sprint will not include this.

**Comment by hallahan** [comment]
I'm thinking we might want to use DownloadManager instead:

http://developer.android.com/reference/android/app/DownloadManager.html

http://blog.vogella.com/2011/06/14/android-downloadmanager-example/
http://www.mysamplecode.com/2012/09/android-downloadmanager-example.html
http://www.programcreek.com/java-api-examples/index.php?api=android.app.DownloadManager
http://www.compiletimeerror.com/2013/11/download-manager-in-android-with-example.html#.VRH7aZPF8Wc

**Comment by hallahan** [comment]
After digging into DownloadManager - an excellent tool that does everything we need, there is one crucial part that it is missing. It does not do HTTP POSTs. Only HTTP GET. The usage of Overpass I am used to for getting data is via a POST. Two options are now:

1. Find another way to download using HTTP in Android. Hopefully not having to implement all of the details that DownloadManager does.

2. See if we can get what we need from Overpass via a GET request.

**Comment by hallahan** [comment]
Here is an example of a GET URL that works:

http://overpass-api.de/api/interpreter?data=(way[building](47.66924559516471,-122.38838195800781,47.671730901355055,-122.3812687397003);way[highway](47.66924559516471,-122.38838195800781,47.671730901355055,-122.3812687397003););out%20meta;%3E;out%20meta%20qt;

**Comment by hallahan** [comment]
Worked out an example showing how to dow downloads via Overpass:

https://github.com/hallahan/DownloadManagerTest

**Comment by hallahan** [comment]
Asked the Overpass folks why we aren't getting the file size in a response:

https://github.com/drolbr/Overpass-API/issues/204

**Comment by dalekunce** [comment]
This is awesome. The UI needs a little cleanup, I think you need something that confirms the user wants to get the osm for the bounding box. I would also have something similar to the overpass API that warns of large downloads, say over 2mb.

**Comment by dalekunce** [comment]
Based on some user tests this needs a confirm dialog. Users end up with lots of extraneous osm files on the phone. This would also be made better by tying the UI to issue #51
