### ISSUE TITLE
zoom to last edit

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/openmapkit#35]
After a successful form save. Next time user opens OMK zoom to last edit area if the form name is the same.

**Comment by hallahan** [comment]
#39 will solve this. Do you want to: 

1. Zoom to wherever the map was last (simple)
2. Keep track of wherever the map was last for a given form and zoom there. (Not hard to implement, maybe confusing for user?)

**Comment by hallahan** [comment]
Done via #39
