### ISSUE TITLE
Map Opens to Last Location by Default

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/openmapkit#39]

**Comment by hallahan** [comment]
Should we though? You can always press the locate button. 

There are 2 other great options:

1. Zoom to where the data is
2. Zoom to wherever the map was last. 

Keeping track of wherever the map was last would make a consistent UX with Google and Apple Maps.

See #32

**Comment by dalekunce** [comment]
I like option 2 that will keep with normal mapping practice.

**Comment by hallahan** [comment]
Ok, let's do that and zoom to the users location if there is no previous saved location.

When we get the OSM options panel, selecting a data set should zoom to the data set. #27

**Comment by hallahan** [comment]
If there is no previous saved location, we zoom to the user's location. In doing such, I'm going to also light up the locate button if the location gathering is on and the beacon is up on the map.

**Comment by hallahan** [comment]
I need a new PNG from Naomi to light up the button. Not doing that now.
