### ISSUE TITLE
Ona Delievery of VM or AMI to RedCross

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKit#5]
We need to hash out the details of this deliverable, including how to handle the open sourcing (or not) of this backend. @mberg, @dalekunce, @mikeleech, @jharpster  - thoughts?

Options:

1. Just have Ona host the data and not worry about it.

2. Keep closed source, provide non-disclosure, deliver AMI & VM.

3. Ona manage EC2 & RDS Instance on RedCross AWS.

4. Integrate OSM bit in the older, open source API.

5. Ona open source the backend, keep new Zebra web app proprietary.

**Comment by dalekunce** [comment]
@mberg is working on the diagram and plan for this.
