### ISSUE TITLE
Need a Logo

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKit#55]
@jharpster we need to get naomi to make us a logo :)

**Comment by hallahan** [comment]
@dalekunce - which icon did you decide on for the app?

https://www.dropbox.com/s/6xpchx8ahmkfva0/OMK_log_vector.pdf?dl=0

**Comment by dalekunce** [comment]
@hallahan can you add the logo to the next build that you do.

**Comment by hallahan** [comment]
Yes.

**Comment by dalekunce** [comment]
![omk_logo_final](https://cloud.githubusercontent.com/assets/1913857/9140528/be20cbdc-3ce6-11e5-918d-6e051b29e0a5.png)
