### ISSUE TITLE
Images For Wiki

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/openmapkit#6]
There is no easy way to upload images to the Github cloud to refer to in the wiki. So, we can just add images to this issue and refer to the url in other places, like the wiki.

![screenshot 2015-03-02 12 12 52](https://cloud.githubusercontent.com/assets/556367/6449432/7adc4c30-c0d5-11e4-8fcf-b638176a35b7.png)

**Comment by hallahan** [comment]
![screenshot 2015-03-02 12 17 17](https://cloud.githubusercontent.com/assets/556367/6449521/17246f64-c0d6-11e4-8f43-940b1f31827a.png)

**Comment by jj0hns0n** [comment]
![upload_to__https___api_openstreetmap_org_api_0_6___and___java_openstreetmap_editor](https://cloud.githubusercontent.com/assets/506078/7143538/1c0c3e68-e295-11e4-884b-09c64e5b80aa.png)
![st__lucia_buildings](https://cloud.githubusercontent.com/assets/506078/7143539/1c3d8450-e295-11e4-9177-27a452bd157e.png)
![st__lucia_buildings_and_slack](https://cloud.githubusercontent.com/assets/506078/7143542/1c69f2a6-e295-11e4-9703-e07553d2989e.png)
![st__lucia_buildings_and_slack_6](https://cloud.githubusercontent.com/assets/506078/7143541/1c68f860-e295-11e4-8e3b-a0f500d2840d.png)
![st__lucia_buildings_and_slack_5](https://cloud.githubusercontent.com/assets/506078/7143540/1c6769b4-e295-11e4-850b-75b50af89742.png)
![st__lucia_buildings_and_slack_4](https://cloud.githubusercontent.com/assets/506078/7143544/1c6c2558-e295-11e4-9c8a-b8ecadfb1fc1.png)
![st__lucia_buildings_and_slack_3](https://cloud.githubusercontent.com/assets/506078/7143543/1c6c021c-e295-11e4-9583-6300e9b4920e.png)
![st__lucia_buildings_and_slack_2](https://cloud.githubusercontent.com/assets/506078/7143545/1c6d6904-e295-11e4-912b-1fad9ca32e79.png)
![st__lucia_buildings_and_slack_1](https://cloud.githubusercontent.com/assets/506078/7143546/1cc9a7d2-e295-11e4-9885-95314ce2c4f0.png)
![st__lucia_buildings_and_java_openstreetmap_editor](https://cloud.githubusercontent.com/assets/506078/7143548/1ccc1ce2-e295-11e4-93f7-77ddab11ead4.png)
![st__lucia_buildings_and_java_openstreetmap_editor_2](https://cloud.githubusercontent.com/assets/506078/7143551/1cccf11c-e295-11e4-9705-4645160deecc.png)
![st__lucia_buildings_and_java_openstreetmap_editor_1](https://cloud.githubusercontent.com/assets/506078/7143547/1ccb0190-e295-11e4-80ed-307093666fd2.png)
![sm-g925t_and_ortelius](https://cloud.githubusercontent.com/assets/506078/7143549/1ccc9d48-e295-11e4-8f70-ed242836e8f4.png)
![sm-g925t_and_applications](https://cloud.githubusercontent.com/assets/506078/7143550/1ccd2682-e295-11e4-8fc7-07327a62a3c1.png)
![screenshot_4_14_15__10_24_am](https://cloud.githubusercontent.com/assets/506078/7143552/1cf3858e-e295-11e4-8c13-66cd77653a1e.png)
![overpass_turbo_and_ortelius_ _node_ _181x27](https://cloud.githubusercontent.com/assets/506078/7143553/1cf8c8e6-e295-11e4-8553-d855783872f7.png)
![ortelius_st__lucia](https://cloud.githubusercontent.com/assets/506078/7143554/1cf91ddc-e295-11e4-942f-a93bca246078.png)
![ona](https://cloud.githubusercontent.com/assets/506078/7143555/1cfaeca2-e295-11e4-94c6-1b8e94c2a1cb.png)
![ona_1](https://cloud.githubusercontent.com/assets/506078/7143556/1cfcee76-e295-11e4-8283-c379aefc8b6d.png)
![java_openstreetmap_editor_and_ortelius_ _java_ _181x27](https://cloud.githubusercontent.com/assets/506078/7143557/1d0137c4-e295-11e4-8afb-36f1adf6f80d.png)
![home](https://cloud.githubusercontent.com/assets/506078/7143558/1d1faeb6-e295-11e4-8976-3ba880107d4c.png)
![__java_openstreetmap_editor_and_ortelius_ _java_ _181x27](https://cloud.githubusercontent.com/assets/506078/7143559/1d20df84-e295-11e4-898e-86649034c55d.png)
![__java_openstreetmap_editor_and_ortelius_ _java_ _181x27_1](https://cloud.githubusercontent.com/assets/506078/7143560/1d213362-e295-11e4-9843-9cad78bbb6ec.png)

**Comment by jj0hns0n** [comment]
![screenshot_2015-04-14-09-47-43](https://cloud.githubusercontent.com/assets/506078/7143724/e07ebd7a-e295-11e4-8c61-8730c4cf53cb.png)
![screenshot_2015-04-14-09-48-00](https://cloud.githubusercontent.com/assets/506078/7143725/e08011e8-e295-11e4-8df4-53db84657b5c.png)
![screenshot_2015-04-14-09-48-46](https://cloud.githubusercontent.com/assets/506078/7143726/e083737e-e295-11e4-8524-37c63187801f.png)
![screenshot_2015-04-14-09-48-55](https://cloud.githubusercontent.com/assets/506078/7143727/e08429cc-e295-11e4-8525-8f9569b01f20.png)
![screenshot_2015-04-14-09-49-07](https://cloud.githubusercontent.com/assets/506078/7143728/e0854690-e295-11e4-8ddf-0ee8b1c77daa.png)
![screenshot_2015-04-14-09-50-24](https://cloud.githubusercontent.com/assets/506078/7143729/e08654d6-e295-11e4-9bca-abbb9f074a80.png)
![screenshot_2015-04-14-09-50-28](https://cloud.githubusercontent.com/assets/506078/7143730/e0955940-e295-11e4-8152-f5128f0374f1.png)
![screenshot_2015-04-14-09-50-45](https://cloud.githubusercontent.com/assets/506078/7143731/e0964bde-e295-11e4-850b-b41c01306b51.png)
![screenshot_2015-04-14-09-50-50](https://cloud.githubusercontent.com/assets/506078/7143732/e098c8a0-e295-11e4-871d-cdd6cc18747b.png)
![screenshot_2015-04-14-09-50-54](https://cloud.githubusercontent.com/assets/506078/7143733/e099c5b6-e295-11e4-8143-c2854cf093c7.png)
![screenshot_2015-04-14-09-51-12](https://cloud.githubusercontent.com/assets/506078/7143746/e10a4426-e295-11e4-857f-932854bfd6b1.png)
![screenshot_2015-04-14-09-51-15](https://cloud.githubusercontent.com/assets/506078/7143734/e09dfb36-e295-11e4-85b5-c6f7d9107b3c.png)
![screenshot_2015-04-14-09-51-20](https://cloud.githubusercontent.com/assets/506078/7143735/e0ab1320-e295-11e4-970a-2098b7d98b3c.png)
![screenshot_2015-04-14-09-51-55](https://cloud.githubusercontent.com/assets/506078/7143736/e0ab7f90-e295-11e4-9835-6eedc6beda0e.png)
![screenshot_2015-04-14-09-52-00](https://cloud.githubusercontent.com/assets/506078/7143737/e0ae9540-e295-11e4-8b4a-2a44d0e58618.png)
![screenshot_2015-04-14-09-52-11](https://cloud.githubusercontent.com/assets/506078/7143738/e0aff584-e295-11e4-9438-0490e06decfd.png)
![screenshot_2015-04-14-10-25-12](https://cloud.githubusercontent.com/assets/506078/7143739/e0b5c284-e295-11e4-894e-72a68e4d7373.png)
![screenshot_2015-04-14-10-25-37](https://cloud.githubusercontent.com/assets/506078/7143740/e0c38054-e295-11e4-83c7-84211150720e.png)
![screenshot_2015-04-14-10-26-34](https://cloud.githubusercontent.com/assets/506078/7143741/e0c3eb20-e295-11e4-8ae2-4b9e8dd615df.png)
![screenshot_2015-04-14-10-26-48](https://cloud.githubusercontent.com/assets/506078/7143743/e0c56306-e295-11e4-8f00-191cd286e070.png)
![screenshot_2015-04-14-10-26-51](https://cloud.githubusercontent.com/assets/506078/7143742/e0c46262-e295-11e4-9a87-eda6c4c94170.png)
![screenshot_2015-04-14-10-26-54](https://cloud.githubusercontent.com/assets/506078/7143744/e0d127ea-e295-11e4-8942-70d3aa81020a.png)
![screenshot_2015-04-14-10-26-59](https://cloud.githubusercontent.com/assets/506078/7143745/e0dbe70c-e295-11e4-8859-d5aa4676cd32.png)

**Comment by jj0hns0n** [comment]
![screenshot_2015-04-14-10-27-04](https://cloud.githubusercontent.com/assets/506078/7143801/41397326-e296-11e4-9a7e-c70b0de7b779.png)
![screenshot_2015-04-14-10-27-09](https://cloud.githubusercontent.com/assets/506078/7143802/4139adc8-e296-11e4-9560-64da5eaa294e.png)
![screenshot_2015-04-14-10-27-14](https://cloud.githubusercontent.com/assets/506078/7143800/4138389e-e296-11e4-96c0-2f1ab8342715.png)
![screenshot_2015-04-14-10-28-53](https://cloud.githubusercontent.com/assets/506078/7143799/4137deda-e296-11e4-8d41-6a1e3dabdd4a.png)
![screenshot_2015-04-14-10-29-54](https://cloud.githubusercontent.com/assets/506078/7143803/413ac1e0-e296-11e4-96fb-d7536e4c979f.png)
![screenshot_2015-04-14-10-29-57](https://cloud.githubusercontent.com/assets/506078/7143804/413beea8-e296-11e4-8a30-44c1d09ee212.png)
![screenshot_2015-04-14-10-30-01](https://cloud.githubusercontent.com/assets/506078/7143805/414ba56e-e296-11e4-86a7-c8f83ac35b7e.png)
![screenshot_2015-04-14-10-30-05](https://cloud.githubusercontent.com/assets/506078/7143807/4150b9d2-e296-11e4-9dd2-0048f2eb1ed6.png)
![screenshot_2015-04-14-10-30-23](https://cloud.githubusercontent.com/assets/506078/7143806/414c9866-e296-11e4-984c-2a78a7a20b76.png)
![screenshot_2015-04-14-10-30-30](https://cloud.githubusercontent.com/assets/506078/7143808/41510d38-e296-11e4-904a-dee165b6b245.png)
![screenshot_2015-04-14-10-30-39](https://cloud.githubusercontent.com/assets/506078/7143810/41526b74-e296-11e4-81cd-257c1654a542.png)
![screenshot_2015-04-14-10-30-43](https://cloud.githubusercontent.com/assets/506078/7143809/4151a234-e296-11e4-82b9-3fbbf9abc36e.png)
![screenshot_2015-04-14-10-31-02](https://cloud.githubusercontent.com/assets/506078/7143812/4161c254-e296-11e4-81e6-f52e523e63a5.png)
![screenshot_2015-04-14-10-31-43](https://cloud.githubusercontent.com/assets/506078/7143811/41619680-e296-11e4-94c7-6e6abbd6f1a9.png)
![screenshot_2015-04-14-10-31-51](https://cloud.githubusercontent.com/assets/506078/7143813/41672dac-e296-11e4-943c-a46cff5ec395.png)
![screenshot_2015-04-14-10-31-56](https://cloud.githubusercontent.com/assets/506078/7143814/4167b812-e296-11e4-9301-52f662c61f94.png)
![screenshot_2015-04-14-10-32-16](https://cloud.githubusercontent.com/assets/506078/7143816/416b2074-e296-11e4-9a77-87f3c998d6bc.png)
![screenshot_2015-04-14-10-32-25](https://cloud.githubusercontent.com/assets/506078/7143815/416a117a-e296-11e4-87c4-2c6371c544d9.png)
![screenshot_2015-04-14-10-32-39](https://cloud.githubusercontent.com/assets/506078/7143818/41749b54-e296-11e4-80d3-9fd211ac7d3c.png)
![screenshot_2015-04-14-10-32-48](https://cloud.githubusercontent.com/assets/506078/7143817/4173eb64-e296-11e4-86df-eaa60e757a38.png)
![screenshot_2015-04-14-10-32-55](https://cloud.githubusercontent.com/assets/506078/7143819/417ac402-e296-11e4-85d0-0ea86fcf2ab5.png)
![screenshot_2015-04-14-10-32-57](https://cloud.githubusercontent.com/assets/506078/7143820/417c41f6-e296-11e4-9e45-7a5e3ec22bfc.png)
![screenshot_2015-04-14-10-33-01](https://cloud.githubusercontent.com/assets/506078/7143822/41822dbe-e296-11e4-8bf9-01f0eabcbbbb.png)
![screenshot_2015-04-14-10-33-05](https://cloud.githubusercontent.com/assets/506078/7143821/4181e28c-e296-11e4-9679-d36259d14683.png)
![screenshot_2015-04-14-10-33-09](https://cloud.githubusercontent.com/assets/506078/7143823/418bc694-e296-11e4-92c4-9acf989c95e9.png)
![screenshot_2015-04-14-10-33-14](https://cloud.githubusercontent.com/assets/506078/7143824/418dea64-e296-11e4-8939-3fc81b30facd.png)
![screenshot_2015-04-14-10-34-28](https://cloud.githubusercontent.com/assets/506078/7143825/418fd0d6-e296-11e4-9e9e-1e9c4af0ac77.png)
![screenshot_2015-04-14-10-34-34](https://cloud.githubusercontent.com/assets/506078/7143826/41946380-e296-11e4-9a4f-0c4ef0ed2e1e.png)
![screenshot_2015-04-14-10-34-38](https://cloud.githubusercontent.com/assets/506078/7143827/41a474d2-e296-11e4-86d7-5775b476f9ad.png)

**Comment by jj0hns0n** [comment]
![ona_and_openoffice](https://cloud.githubusercontent.com/assets/506078/7144400/19f69dee-e29a-11e4-9ef2-804fb4b70e18.png)
![ona_and_slack](https://cloud.githubusercontent.com/assets/506078/7144401/1a104474-e29a-11e4-89a1-6cbee9acdb44.png)
![ona](https://cloud.githubusercontent.com/assets/506078/7144402/1a193dea-e29a-11e4-8e37-6439f1a1c8c0.png)
![st_lucia_buildings_omk_-_google_sheets_and_slack_1](https://cloud.githubusercontent.com/assets/506078/7144404/1a195dc0-e29a-11e4-9034-9da6ea439c5f.png)
![st_lucia_buildings_omk_-_google_sheets_and_slack_2](https://cloud.githubusercontent.com/assets/506078/7144405/1a1ae4a6-e29a-11e4-9467-ccc7404feaf5.png)
![st_lucia_buildings_omk_-_google_sheets_and_slack](https://cloud.githubusercontent.com/assets/506078/7144403/1a194880-e29a-11e4-923a-f846cf81f379.png)
![upload_to__https___api_openstreetmap_org_api_0_6___and___java_openstreetmap_editor](https://cloud.githubusercontent.com/assets/506078/7144406/1a1d7e00-e29a-11e4-8d43-f3a676944832.png)

**Comment by hallahan** [comment]
![screenshot_2015-04-30-03-37-07](https://cloud.githubusercontent.com/assets/556367/7404896/31078528-ee9f-11e4-851f-a8943a66584b.png)

**Comment by hallahan** [comment]
![screenshot_2015-04-30-03-36-58](https://cloud.githubusercontent.com/assets/556367/7404898/37291566-ee9f-11e4-9f23-b5eee42bdfea.png)

**Comment by hallahan** [comment]
![screenshot 2015-04-29 16 38 11](https://cloud.githubusercontent.com/assets/556367/7404920/875f2386-ee9f-11e4-9d00-773eb8ac481b.png)
![screenshot 2015-04-29 16 35 47](https://cloud.githubusercontent.com/assets/556367/7404922/8c1d221a-ee9f-11e4-8bd8-d289e85a1fa9.png)
![screenshot 2015-04-29 16 01 53](https://cloud.githubusercontent.com/assets/556367/7404927/8fcfdbaa-ee9f-11e4-98a8-58b5a74e5433.png)
![screenshot 2015-04-29 15 58 57](https://cloud.githubusercontent.com/assets/556367/7404929/9418893c-ee9f-11e4-9249-b684ff33e16a.png)

**Comment by hallahan** [comment]
![screenshot 2015-04-29 21 08 22](https://cloud.githubusercontent.com/assets/556367/7406236/e86fcefa-eeb3-11e4-9b71-f90a0e3e593a.png)

**Comment by hallahan** [comment]
<img width="512" alt="screenshot 2016-05-16 14 49 00" src="https://cloud.githubusercontent.com/assets/556367/15690925/d28fac7a-273a-11e6-8677-5d07728c29c7.png">

**Comment by hallahan** [comment]
<img width="499" alt="omk-server-form-title" src="https://cloud.githubusercontent.com/assets/556367/15691046/74a3bdda-273b-11e6-80fd-796915978b6c.png">

**Comment by hallahan** [comment]
![2016-05-31 22 02 22](https://cloud.githubusercontent.com/assets/556367/15692147/a74504fa-2741-11e6-87d5-11fbe394dea2.png)

**Comment by hallahan** [comment]
![2016-05-31 22 23 23](https://cloud.githubusercontent.com/assets/556367/15692507/b73fb48e-2743-11e6-8288-8739553609d9.png)

**Comment by hallahan** [comment]
![2016-05-31 22 41 23](https://cloud.githubusercontent.com/assets/556367/15692919/2f0325d0-2746-11e6-9304-36fb23886504.png)

**Comment by hallahan** [comment]
![2016-05-31 22 54 07](https://cloud.githubusercontent.com/assets/556367/15693150/ede2b41a-2747-11e6-833a-a562c8f88bc5.png)
