### ISSUE TITLE
Refresh of offline data after non-modification of OSM tag

### ISSUE THREAD

**Issue by ivangayton** [AmericanRedCross/OpenMapKit#60]
After selecting vector, selecting a specific tag, not modifying it but rather simply returning to the attribute view, the vectors no longer draw.

When returning to the layer selector, the vector in question is still checked, but must be unchecked and rechecked before it will return to service.

Yo.

**Comment by hallahan** [comment]
I've fixed this issue without having to reparse and reload the OSM XML. This means there will be no user intervention or waiting to load data. It just works now : )
