### ISSUE TITLE
should keys outside of survey display?

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKit#66]
If a key (and value) exist on a building but not in the survey, they still show up when you're swiping through the survey. But you can't edit them. You just have to swipe more. Should they be hidden from the user? I could argue both ways I think.

![screenshot_2015-06-03-12-32-09](https://cloud.githubusercontent.com/assets/4806884/7965772/af06eda6-09ed-11e5-97fe-8f4d8b6c8304.png)

**Comment by hallahan** [comment]
I think they should be shown. The idea is that the edit-ability is based on the XForm, but there might be tags with something important to know about.
