### ISSUE TITLE
Edit Tags Button for No Tags Use Case

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKit#7]
Sometimes a feature might not have any tags. Right now, if you click on a tag, it shows you the given tag in the tag swipe activity. Then you can swipe to see others.

If there are no tags, we need a button you can press. Also, there should be a button anyway.

**Comment by dalekunce** [comment]
@hallahan I don't think this would ever occur if you were operating in conjunction with ODK. This is a OMK stand alone only problem right.

**Comment by hallahan** [comment]
If you do not specify any tags in the XForm, this will fail. Having no tags specified is a valid use case. For example, you might want a survey where the user just selects an OSM feature but does not want to edit tags. This may be a common use case, especially if you have a survey question that is to be treated like a "check in" as @mberg envisions.
