### ISSUE TITLE
Update Mapbox Android SDK

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKit#73]
Lots has changed since February. Let's see if we can leverage work done since then. In particular, markers work better, and this work will be needed for the POI feature #31

**Comment by mberg** [comment]
Realize this is unrelated.  We have some PR's coming with a bunch of fixes
to the current tool.  It might be get them pulled in before doing this
switch.

**Comment by hallahan** [comment]
@mberg - could you coordinate with me the features in these PR, the branches, and the expected date? I'm going to do this on a branch first, and I'll document how "breaking" it is. We can work on pulling in your changes, however, this really needs to be done for POI feature.

**Comment by mberg** [comment]
Cool.  It's mostly some bug fixes and some extra work on the proximity
feature we added.  It would be good to setup a call to discuss.    Probably
would be good to setup calls around OMK in general so we can coordinate
approach if we're hoping to make this into an opensource project with legs.

On Wed, Aug 5, 2015 at 10:25 PM, Nicholas Hallahan <notifications@github.com

**Comment by hallahan** [comment]
:+1:
