### ISSUE TITLE
OMK Community Call

### ISSUE THREAD

**Issue by mberg** [AmericanRedCross/OpenMapKit#74]
I think we're all excited by the potential of OMK.  We're starting to invest resources into making it better and our excited to continue to contribute to this project.

As a project, I think it would be great to identify the other groups currently interested in OMK and who are planning to contribute to it.  Having a shared sense of roadmap and the ability to bounce ideas off a community before we start making important design decisions and just doing PR's would be extremely helpful.

So to summarize, would people be open to setting up an initial community call around OMK?  Goal of the call would be the following

* Intros - who is currently interested in using and contributing to OMK?  Why?
* Shared Roadmap - plans for OMK over the next few months?  Are there any specific projects that are going to drive certain features?  What features are groups interested in contributing?
* Code Governance - Basic strategies around discussing features that might have an important architectural or design impact.   

I realize this project is still very young so not trying to jump the gun and make this too formal.   I just think we're past the point of concept now and starting to build a community around this and leveraging OSM in general in new ways could have a lot of benefit.

**Comment by mwhewett** [comment]
Matt- thanks for the offer.  CRC would be interested in participating. We don’t have a lot of experience here with ODK at CRC but OMK may be a useful tool for us both domestically and internationally.  We have people very interested having a standardized mobile data collection tool for our programs.  We could potentially assist with testing, etc. Please include me in the call.  Matt

Matt Hewett
Tel 613.740.5024 | BB 613.295.6857

**Comment by mikelmaron** [comment]
:thumbsup:

**Comment by dalekunce** [comment]
Community Road Map meeting will be October 26th, 1-5pm at American Red Cross in DC.

Contact me if you would like to be included.

**Comment by wonderchook** [comment]
@dalekunce I'd like to be included. I happen to be in DC that day.

**Comment by mberg** [comment]
@dalekunce - please count me in.  I'll have to call in if that's possible

**Comment by mwhewett** [comment]
Dale- please send the agenda if available/ if it is call- in friendly. Matt

Sent from my iPhone

On Sep 11, 2015, at 4:01 PM, Dale Kunce <notifications@github.com<mailto:notifications@github.com>> wrote:


Community Road Map meeting will be October 26th, 1-5pm at American Red Cross in DC.

Contact me if you would like to be included.

�

**Comment by mberg** [comment]
@dalekunce - I won't be able to join in person but would love to attend call in if possible.  If there is an agenda can it be shared along with call in details?  

Thanks,

Matt

**Comment by mberg** [comment]
Hi did this happen?
