### ISSUE TITLE
ODK Collect question

### ISSUE THREAD

**Issue by mberg** [AmericanRedCross/OpenMapKit#80]
Apologize for using an issue to ask this question.

Right now we are still using a modified version of ODK to use OMK.  Has the OMK related code worked itself into master on ODK Collect yet?  @hallahan @dalekunce Do you know the status on this?

If so, we should update the docs on the wiki for this.

**Comment by dalekunce** [comment]
OMK has been pushed to ODK master. We need to do some more documentation so that ODK will push the update to the play store. @hallahan is working on those needed pieces. Once ODK is updated in the play store we will push OMK to the play store.

**Comment by mberg** [comment]
Thanks @dalekunce so to confirm - the OMK specific code should now be part of ODK Collect.  So we can use the regular ODK collect from the play store and it will work with OMK.

**Comment by dalekunce** [comment]
while the changes for OMK have been pushed to ODK master they are not yet in the version in the play store. You will still need to install the customized ODK version from the OMK wiki.

**Comment by mberg** [comment]
Thanks for the clarity
