### ISSUE TITLE
if screen rotates in map view, OSM layer "breaks"

### ISSUE THREAD

**Issue by mikelmaron** [AmericanRedCross/OpenMapKit#83]
If the screen rotates from portrait to landscape view (or vice versa) all the OSM features disappear. only way to get them back is to remove the osm data layer, then add it back. prevention step is to turn off rotation on the phone. mowr better would be proper handling of this redraw.

**Comment by dalekunce** [comment]
Replicated the issue on a Nexus 5.

**Comment by hallahan** [comment]
Fixed via https://github.com/AmericanRedCross/OpenMapKit/commit/76fae1174c5d205c338c2e270a6acfa520a8c05f
