### ISSUE TITLE
option to clear selected answer?

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKit#9]
when filling out a survey and adjusting tags for a feature and if it's a non-required select_one or select_multiple, is it possible to add a way to clear all the selection(s) if you accidentally click an option and actually don't want to submit anything for that question (i.e. leave it blank)?

**Comment by hallahan** [comment]
I wonder where in the UI this would make sense?

**Comment by danbjoseph** [comment]
it shouldn't need an additional UI component. just that a repeat press on the answer clears it. and allow to clear down to no selections (so you can proceed past a non-required question without answering).

for example "Does this building have a soft story? [ yes / no ]" and you accidentally click an answer but then decide you're not sure and want to clear the answer but still complete other questions about the feature.

**Comment by hallahan** [comment]
Cool, makes sense to me.

**Comment by hallahan** [comment]
@danbjoseph You will now be able to toggle off a selected radio button on the next OpenMapKit release.
