### ISSUE TITLE
Wiki PR: Update to Workflow Page

### ISSUE THREAD

**Issue by rbanick** [AmericanRedCross/OpenMapKit#94]
Since github doesn't allow pull requests to wiki pages I'm putting this here. I've gone through the Workflow wiki page and made some updates. There are two kinds.

1. Annotation of existing pictures to make un-illustrated steps clearer
2. Replacing old Ona screenshots with screenshots of the new Ona interface, where possible.

Attached is the new markdown file. If you could review and, if satisfactory, push to the master Wiki page I'd be most appreciative.

Uploaded as a .txt as github rejects .md attachments.
[Workflow.txt](https://github.com/AmericanRedCross/OpenMapKit/files/32677/Workflow.txt)

**Comment by dalekunce** [comment]
Looking good @rbanick
